# Generated by Django 3.0.2 on 2020-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCPD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('fee_segment', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('total_teachers', models.CharField(max_length=100)),
                ('total_students', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
