# Generated by Django 3.0.2 on 2020-08-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_schoolcpd'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('total_clicks', models.IntegerField()),
                ('day', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
