# Generated by Django 3.0.7 on 2020-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tech', models.CharField(max_length=60)),
                ('board', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=30)),
                ('grade', models.IntegerField()),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('lesson', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('click', models.IntegerField()),
            ],
        ),
    ]
