# Generated by Django 3.0.7 on 2020-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('school', models.CharField(max_length=60)),
                ('fee', models.CharField(default='', max_length=60)),
                ('teacher', models.IntegerField()),
                ('students', models.IntegerField()),
                ('date', models.DateField()),
                ('click', models.IntegerField()),
            ],
        ),
    ]
