# Generated by Django 3.0.7 on 2020-08-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fee',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
