# Generated by Django 3.0.7 on 2020-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200808_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tech', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='fee',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
