# Generated by Django 3.0.7 on 2020-08-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school1'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('curriculum', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('grade', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=70)),
                ('week', models.IntegerField()),
                ('day', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=60)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.admins')),
            ],
        ),
        migrations.DeleteModel(
            name='lesson',
        ),
        migrations.DeleteModel(
            name='school',
        ),
    ]
